CompileFlags:
  Add:
    - "-std=c++26"
    - "-freflection"
    - "--gcc-toolchain=/usr"
    - "-isystem"
    - "/usr/include/c++/16"
    - "-isystem"
    - "/usr/include/c++/16/x86_64-redhat-linux"
  Remove:
    - "-fmodules-ts"
    - "-fmodule-mapper*"
    - "-fdeps-format*"
    - "-fpreprocessed"
  Compiler: g++

Index:
  StandardLibrary: Yes
